### ISSUE TITLE
Missing AGR-18 Lynchpin

### ISSUE THREAD

**Issue by sewerpig** [woodendoors7/NuclearOptionDocs#1]
The rockets from the AGR-18 rocket pod aren't listed in this wiki. They're in the in-game encyclopedia, so it should be a quick addition.

**Comment by woodendoors7** [comment]
It's not as easy as copy pasting text from the encyclopedia, as I write the text and add more information. I haven't had much time lately, so I wasn't able to write new articles. Feel like contributing?

**Comment by sewerpig** [comment]
Sure, I was actually even wondering where you got the text from the json files from, didn't realize you were writing them actively yourself. I might take a crack at making a basic page for it today.
